name: Add Secrets

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "Value of MY_SECRET - $MY_SECRET"
        env: 
          API_KEY: ${{ secrets.SHEETS_API }}
